// import React from 'react';

// export const UserData = [
//   {
//     id: '1',
//     departure_place: 'Kigali',
//     destination: 'Musanze',
//     departure_date: '2022-05-05',
//     return_date: '2022-05-10',
//     travelReason: 'Business',
//     status: 'Approved',
//   },
//   {
//     id: '2',
//     departure_place: 'Kigali',
//     destination: 'Muhanga',
//     departure_date: '2022-07-05',
//     return_date: '2022-07-12',
//     travelReason: 'Family Visit',
//     status: 'Approved',
//   },
//   {
//     id: '3',
//     departure_place: 'Kigali',
//     destination: 'Bugesera',
//     departure_date: '2022-06-01',
//     return_date: '2022-06-13',
//     travelReason: 'Leisure',
//     status: 'Pending',
//   },
//   {
//     id: '4',
//     departure_place: 'Rubavu',
//     destination: 'Kigali',
//     departure_date: '2022-08-07',
//     return_date: '2022-12-10',
//     travelReason: 'Visit',
//     status: 'Rejected',
//   },
//   {
//     id: '5',
//     departure_place: 'Nyagatare',
//     destination: 'Kampala',
//     departure_date: '2022-07-05',
//     return_date: '2022-09-10',
//     travelReason: 'Business',
//     status: 'Pending',
//   },
//   {
//     id: '6',
//     departure_place: 'Kigali',
//     destination: 'Nairobi',
//     departure_date: '2022-05-05',
//     return_date: '2022-12-01',
//     travelReason: 'Visa Application',
//     status: 'Pending',
//   },
//   {
//     id: '7',
//     departure_place: 'Bujumbura',
//     destination: 'Goma',
//     departure_date: '2022-11-05',
//     return_date: '2022-12-10',
//     travelReason: 'Tour',
//     status: 'Pending',
//   },
// ];
